In [1]:
import numpy as np

#visuals
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from mpl_toolkits.mplot3d import Axes3D
import matplotlib
matplotlib.rcParams.update({'font.size': 10})

#Hugo code
import Utility
import PythonKEX

In [2]:
# test vectorization
hbin = np.array([0,0,0,0])
print(Utility.imageBinFromHistogramBin(hbin))
histoBins = np.swapaxes([hbin, hbin+1], 0, 1)
print("histobins\n", histoBins)
print("histobins shape", histoBins.shape)
imgBins = Utility.imageBinFromHistogramBin(histogramBin=histoBins)
print("image bins\n", imgBins)

[  0 100   1]
histobins
 [[0 1]
 [0 1]
 [0 1]
 [0 1]]
histobins shape (4, 2)
image bins
 [[  0   1]
 [100  75]
 [  1   2]]


In [3]:
#points in histogram
fixedPosition = [0,0,0,0]
ranges = []
histogramBins = []
for k,dim in enumerate(Utility.HISTOGRAM_SHAPE):
    ranges.append(np.arange(dim))
    hb = np.zeros((4,dim), dtype=int)+np.reshape(fixedPosition, (4,1))
    hb[k] = np.arange(dim)
    histogramBins.append(hb)

In [5]:
#convert to histoImage points
imageBins = []
for hb in histogramBins:
    print(hb.shape)
    imageBins.append(Utility.imageBinFromHistogramBin(hb))

(4, 14)


NameError: name 'tofbins' is not defined

In [ ]:
#fix r, tof
#let mi and tx vary


mi_step = 1
tx_step = 1
MI, TX = np.meshgrid(np.arange(0,Utility.HISTOGRAM_SHAPE[1], mi_step), np.arange(0,Utility.HISTOGRAM_SHAPE[2],tx_step))
histogramPoints = np.zeros((4, np.prod(MI.shape)), dtype=int)
histogramPoints[1] = MI.flat
histogramPoints[2] = TX.flat

In [ ]:
histoImages = []
titles = []
for ro in [0,-10,10,+50, 100,150]:
    imagePoints = []
    histoImage = np.zeros(shape=Utility.IMAGE_SHAPE,dtype=int)
    titles.append("tofbins at radial offset " + str(ro))
    for tof in range(13):
        histogramPoints[0] = tof
        robin = ro + 200
        histogramPoints[-1] = robin
        imgBins = Utility.imageBinFromHistogramBin(histogramPoints, offsetTOF=False)
        imagePoints.append(imgBins)
        bValid = Utility.bValidImageBin(imgBins)
        validImageBins = imgBins[:,bValid]
        #print(validImageBins[:, validImageBins[0] > 109])
        np.add.at(histoImage, tuple(validImageBins), 1)
    histoImages.append(histoImage)

In [ ]:
#look at histo image
%matplotlib inline
shape = (2,3)
figsize = tuple(np.array(shape)*5)
matplotlib.rcParams.update({'font.size': 10})
Utility.interactImages(histoImages, titles=titles, subplotShape=shape, figsize=np.flip(figsize))

In [ ]:
#repeat 
#fix tx, tof
#let ro and mi vary

mi_step = 1
ro_step = 1
MI,RO = np.meshgrid(np.arange(0,Utility.HISTOGRAM_SHAPE[1], mi_step), np.arange(0,Utility.HISTOGRAM_SHAPE[3],ro_step))
histogramPoints = np.zeros((4, np.size(MI)), dtype=int)
histogramPoints[1] = MI.flat
histogramPoints[3] = RO.flat
print(np.size(MI))

In [ ]:
histoImages = []
titles = []
fractions = np.array([0, 1/10, 1/4, 1/3, 1/2,0.9])
print(fractions)
angles = np.array(fractions*Utility.NUMBER_OF_VIEWS, dtype=int)
print(angles)
for k, tx_bin in enumerate(angles):
    title = "tofbins at tx angle bin " + str(tx_bin) + ", " + str(int(fractions[k]*100)) + " % of halfturn"
    titles.append(title)

for tx_bin in angles:
    imagePoints = []
    histoImage = np.zeros(shape=Utility.IMAGE_SHAPE,dtype=int)

    for tof in range(13):
        histogramPoints[0] = tof
        histogramPoints[2] = tx_bin
        imgBins = Utility.imageBinFromHistogramBin(histogramPoints, offsetTOF=True)
        imagePoints.append(imgBins)
        bValid = Utility.bValidImageBin(imgBins)
        validImageBins = imgBins[:,bValid]
        #print(validImageBins[:, validImageBins[0] > 109])
        np.add.at(histoImage, tuple(validImageBins), 1)
    histoImages.append(histoImage)

In [ ]:
#look at histo image
%matplotlib inline
matplotlib.rcParams.update({'font.size': 10})
shape = (2,3)
figsize = tuple(np.flip(np.array(shape)*5))
Utility.interactImages(histoImages, titles=titles, subplotShape=shape, figsize=figsize)

In [ ]:
#repeat 
#fix mi, tof
#let ro and tx vary

tx_step = 1
ro_step = 1
TX,RO = np.meshgrid(np.arange(0,Utility.HISTOGRAM_SHAPE[2], tx_step), np.arange(0,Utility.HISTOGRAM_SHAPE[3],ro_step))
histogramPoints = np.zeros((4, np.size(TX)), dtype=int)
histogramPoints[2] = TX.flat
histogramPoints[3] = RO.flat
print(np.size(TX))

In [ ]:
histoImages = []
titles = []
segmentMichBins = np.cumsum(Utility.SEGMENT_TABLE) -Utility.SEGMENT_TABLE[0]

for seg,mi in enumerate(segmentMichBins): 
    title = "tofbins at mi bin " + str(mi) + " in seg. " + str(Utility.SEGMENT_OFFSET_MAP[seg])
    titles.append(title)

for mi in segmentMichBins:
    imagePoints = []
    histoImage = np.zeros(shape=Utility.IMAGE_SHAPE,dtype=int)
    for tof in range(13):
        histogramPoints[0] = tof
        histogramPoints[1] = mi
        imgBins = Utility.imageBinFromHistogramBin(histogramPoints)
        imagePoints.append(imgBins)
        bValid = Utility.bValidImageBin(imgBins)
        validImageBins = imgBins[:,bValid]
        #print(validImageBins[:, validImageBins[0] > 109])
        np.add.at(histoImage, tuple(validImageBins), 1)
    histoImages.append(histoImage)

In [ ]:
#look at histo image
%matplotlib inline
matplotlib.rcParams.update({'font.size': 10})
shape = (4,4)
figsize = tuple(np.flip(np.array(shape)*5))
Utility.interactImages(histoImages, titles=titles, subplotShape=shape, figsize=figsize)

In [ ]:
#repeat 
#fix tof
#let ro and tx vary
#let mi vary within segment 1

segmentMichBins = np.cumsum(Utility.SEGMENT_TABLE)-1
segmentMichBins = np.append(0, segmentMichBins)
segmentMichBins = np.append(segmentMichBins, Utility.NUMBER_OF_SINOGRAMS-1)
print(segmentMichBins)
segment = 0

tx_step = 1
ro_step = 1
mi_step = 10
TX,RO,MI = np.meshgrid(np.arange(0,Utility.HISTOGRAM_SHAPE[2], tx_step), 
                             np.arange(0,Utility.HISTOGRAM_SHAPE[3],ro_step),
                            np.arange(segmentMichBins[segment], segmentMichBins[segment+1], mi_step))
histogramPoints = np.zeros((4, np.size(TX)), dtype=int)
histogramPoints[2] = TX.flat
histogramPoints[3] = RO.flat
histogramPoints[1] = MI.flat
print(np.size(TX))

In [ ]:
histoImages = []
titles = []
titles.append("tofbins at segment " + str(Utility.SEGMENT_OFFSET_MAP[segment]))

histoImage = np.zeros(shape=Utility.IMAGE_SHAPE,dtype=int)
for tof in range(13):
    histogramPoints[0] = tof
    imgBins = Utility.imageBinFromHistogramBin(histogramPoints, offsetTOF=True)
    imagePoints.append(imgBins)
    bValid = Utility.bValidImageBin(imgBins)
    validImageBins = imgBins[:,bValid]
    #print(validImageBins[:, validImageBins[0] > 109])
    np.add.at(histoImage, tuple(validImageBins), 1)
histoImages.append(histoImage)

In [ ]:
#look at histo image
%matplotlib inline
matplotlib.rcParams.update({'font.size': 10})
shape = (4,4)
figsize = tuple(np.flip(np.array(shape)*5))
Utility.interactImages(histoImages, titles=titles, subplotShape=shape, figsize=figsize)

In [ ]:
# even distribution from point
# add one count for each bin that could detect the point
#investigate how the histoImage looks

# pick a direction T
# it works for all transaxial angles
# for the tilt, start with direct segments then search, +segments and -segments
# if there are two intersections with the cylinder
# this yields the points A,B, 
# calculate ao, discrete
# calculate segment, discrete
# calculate R, discrete
# calculate the tof bin
# else, some boundary

#seems tricky
#useful but quite complicated
# it is better to use simulations for this

In [ ]:
# for a point source
# each sinogram (include all tofbins) should have 1 or 0 sinuscurves
# the maximum ro is determined by the distance from the z axis of the point source
# the transaxial angle is given by a transaxial perpendicular of the vector from z axis to point source
# the allowable tilts should be symmetric at this ro, tx ( and the closest) tofbin would be 0 )
# then we have another important LOR,where the line goes through the z axis and the point source
# this would determine the range of tof-bins used?
