In [1]:
import numpy as np

In [2]:
def make_matrix(shape):
    return np.reshape(np.arange(np.prod(shape)), shape)

In [3]:
shape = (4,)*3
A = make_matrix(shape)
print("A\n", A)
print("3D diag\n", np.einsum('iii->i',A))
print("3D diag sum\n", np.einsum('iii',A))

A
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]
3D diag
 [ 0 21 42 63]
3D diag sum
 126


In [4]:
shape = (5,) + (2,)*2
B = np.reshape(np.arange(np.prod(shape)), shape)
print("B\n", B)
print("2D diag sums\n", np.einsum('jii->j',B)) #the diagonal sum of each matrix B[j]
print("\n", np.einsum('jii->i',B), np.diag(np.sum(B, axis=0))) # the diagonal, when summing over j
print("dotprods\n", np.einsum('nik, nkj->nij', B,B))

B
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]
2D diag sums
 [ 3 11 19 27 35]

 [40 55] [40 55]
dotprods
 [[[  2   3]
  [  6  11]]

 [[ 46  55]
  [ 66  79]]

 [[154 171]
  [190 211]]

 [[326 351]
  [378 407]]

 [[562 595]
  [630 667]]]


In [5]:
shape = B.shape[:2]
v = np.reshape(np.arange(np.prod(shape)), shape)
v = np.swapaxes(v, 0, 1)
print("B\n", B)
print("v\n", v)
print("dotprods\n", np.einsum('nij,jn->in', B,v))

B
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]
v
 [[0 2 4 6 8]
 [1 3 5 7 9]]
dotprods
 [[  1  23  77 163 281]
 [  3  33  95 189 315]]


In [6]:
C = make_matrix((3,)*2 + (5,) )
print("C\n", C)
print("C[:,:,0]\n",C[:,:,0])
x = make_matrix(C.shape[1:] )
print("x\n", x)
print("dot_prod\n", np.einsum('ijn,jn->in', C,x))

C
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]
C[:,:,0]
 [[ 0  5 10]
 [15 20 25]
 [30 35 40]]
x
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
dot_prod
 [[ 125  158  197  242  293]
 [ 350  428  512  602  698]
 [ 575  698  827  962 1103]]


In [17]:
import numpy as np
shape = (3,3,5)
A = make_matrix(shape)
v = [1,2,3]
print("A\n",A)
print("v\n", v)
print("A[:,:,0]\n", A[:,:,0])
print("A . v\n", np.einsum('kin, i->kn', A,v))

A
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]
v
 [1, 2, 3]
A[:,:,0]
 [[ 0  5 10]
 [15 20 25]
 [30 35 40]]
A . v
 [[ 40  46  52  58  64]
 [130 136 142 148 154]
 [220 226 232 238 244]]


In [21]:
a = {'a':2}
print(a)

{'a': 2}


In [26]:
def f(a,b):
    print(a-b)

In [30]:
f(**{'a':1}, **{'b':4, 'c':2})

TypeError: f() got an unexpected keyword argument 'c'

In [49]:
print(np.einsum('i,i', [1,2,3], [1]))

6
