In [1]:
import representation
import numpy as np

import importlib
importlib.reload(representation)

<module 'representation' from 'C:\\Users\\petct\\Desktop\\Hugo\\Code\\PythonMEX\\representation.py'>

In [2]:
tx = np.pi/3
tilt = {'ro':0, 'radius':1, 'rd':0.2}
A = representation.axes_matrix(tx, **tilt)

In [3]:
print(A)

[[ 0.86172748  0.5         0.        ]
 [-0.4975186   0.8660254   0.        ]
 [ 0.09950372  0.          1.        ]]


In [4]:
B = representation.axes_matrix_inverse(tx, **tilt)
print(B)

[[ 0.87034476 -0.50249378  0.        ]
 [ 0.5         0.8660254   0.        ]
 [-0.08660254  0.05        1.        ]]


In [5]:
print(np.round(np.dot(A,B)).astype(int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [6]:
x,y,a,b = 1,2,3,4
A = representation.data_to_image_matrix(a,b,x,y)
B = representation.image_to_data_matrix(a,b,x,y)
C = np.dot(A,B)
print(A)
print("inverse?\n",B) #only if xx+yy=aa+bb=1
print("dot prod\n", C) 

[[ 4.  3.  0.]
 [-3.  4.  0.]
 [ 2.  0.  1.]]
inverse?
 [[ 4. -3.  0.]
 [ 3.  4.  0.]
 [-8.  6.  1.]]
dot prod
 [[25.  0.  0.]
 [ 0. 25.  0.]
 [ 0.  0.  1.]]


In [7]:
x,y,a,b = 5,2,3,4
A = representation.data_to_image_matrix(a,b,x,y)
B = representation.image_to_data_matrix(a,b,x,y)
C = np.dot(A,B)
print(A)
print("inverse?\n",B) #only if xx+yy=aa+bb=1
print("dot prod\n", C) 

[[ 20.   3.   0.]
 [-15.   4.   0.]
 [  2.   0.   1.]]
inverse?
 [[ 0.8 -0.6  0. ]
 [ 3.   4.   0. ]
 [-1.6  1.2  1. ]]
dot prod
 [[25.  0.  0.]
 [ 0. 25.  0.]
 [ 0.  0.  1.]]


In [8]:
tx, ax = np.pi/3, np.pi/5
kwargs = {'cos_ax': np.cos(ax), 
 'sin_ax': np.sin(ax), 
 'cos_tx': np.cos(tx), 
 'sin_tx': np.sin(tx)}
A = representation.data_to_image_matrix(**kwargs)
B = representation.image_to_data_matrix(**kwargs)
C = np.dot(A,B)
print(A)
print("inverse?\n",B) #only if xx+yy=aa+bb=1
print("dot prod\n", C) 

[[ 0.70062927  0.5         0.        ]
 [-0.4045085   0.8660254   0.        ]
 [ 0.58778525  0.          1.        ]]
inverse?
 [[ 1.07046627 -0.61803399  0.        ]
 [ 0.5         0.8660254   0.        ]
 [-0.62920429  0.36327126  1.        ]]
dot prod
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -5.55111512e-17  1.00000000e+00]]


In [22]:
importlib.reload(representation)
kwargs = {'tx': np.pi/3, 'radius': 1, 'ro':0.1, 'rd':0.4}
A = representation.axes_matrix(**kwargs)
B = representation.axes_matrix_inverse(**kwargs)
C = np.dot(A,B)
print(A)
print("inverse?\n",B) #only if xx+yy=aa+bb=1
print("dot prod\n", C) 

[[ 0.84904286  0.5         0.        ]
 [-0.49019513  0.8660254   0.        ]
 [ 0.19706586  0.          1.        ]]
inverse?
 [[ 0.88334763 -0.51000099  0.        ]
 [ 0.5         0.8660254   0.        ]
 [-0.17407766  0.10050378  1.        ]]
dot prod
 [[1.00000000e+00 5.55111512e-17 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [2.77555756e-17 1.38777878e-17 1.00000000e+00]]


In [9]:
xyz = [0,2,1]
trm = np.dot(A,xyz)
print(trm)

[1.         1.73205081 1.        ]


In [47]:
XYZ = np.array([xyz, xyz, xyz, xyz, xyz]).T
trm = np.dot(A, XYZ)
print(XYZ.shape)
print(trm.shape)
print(trm)

(3, 5)
(3, 5)
[[1.         1.         1.         1.         1.        ]
 [1.73205081 1.73205081 1.73205081 1.73205081 1.73205081]
 [1.         1.         1.         1.         1.        ]]


In [48]:
XYZ = np.array([xyz, xyz, xyz, xyz, xyz]).T
trm = np.tensordot([A]*5, XYZ, axes=(1, 0))
print(XYZ.shape)
print(trm.shape)
#print(trm)

(3, 5)
(5, 3, 5)


In [49]:
np.sum([A]*5, axis=1).shape

(5, 3)

In [61]:
A = np.eye(2)
A[0,1] = 0.1
print(A)
xy = np.array([2, 3])
print("simple dot", np.dot(A,xy))
B = np.array([A, 2*A, 3*A])
L = np.array([xy]*3)
print(np.dot(B,L))

[[1.  0.1]
 [0.  1. ]]
simple dot [2.3 3. ]


ValueError: shapes (3,2,2) and (3,2) not aligned: 2 (dim 2) != 3 (dim 0)

In [62]:
print(B.shape, L.shape)
print("(0,0)\n",np.tensordot(B,L, axes=[0,0]))
#print("(1,0)\n",np.tensordot(B,L, axes=[1,0]))
print("(1,1)\n", np.tensordot(B,L, axes=[1,1]))
#print("(0,1)\n",np.tensordot(B,L, axes=[0,1]))
print("(2,1)\n", np.tensordot(B,L, axes=[2,1]))
#print("((1,2),1)\n", np.tensordot(B,L, axes=[(1,2),1]))
#print("((1,2),0)\n", np.tensordot(B,L, axes=[(1,2),0]))
print("((0,2), (0,1)) \n", np.tensordot(B,L, axes=((0,2), (0,1)) ))

(3, 2, 2) (3, 2)
(0,0)
 [[[12.  18. ]
  [ 1.2  1.8]]

 [[ 0.   0. ]
  [12.  18. ]]]
(1,1)
 [[[2.  2.  2. ]
  [3.2 3.2 3.2]]

 [[4.  4.  4. ]
  [6.4 6.4 6.4]]

 [[6.  6.  6. ]
  [9.6 9.6 9.6]]]
(2,1)
 [[[2.3 2.3 2.3]
  [3.  3.  3. ]]

 [[4.6 4.6 4.6]
  [6.  6.  6. ]]

 [[6.9 6.9 6.9]
  [9.  9.  9. ]]]
((0,2), (0,1)) 
 [13.8 18. ]


In [63]:
my_dot = np.zeros((3,2))
for n in range(3):
    for i in range(2):
        my_dot[n,i] = np.sum(B[n,i,:]*L[n,:])
print(my_dot)

[[2.3 3. ]
 [4.6 6. ]
 [6.9 9. ]]


In [64]:
my_dot2 = np.sum(B*np.expand_dims(L, 1), axis=-1)
print(my_dot2)

[[2.3 3. ]
 [4.6 6. ]
 [6.9 9. ]]


In [65]:
np_dot = np.tensordot(B,L, axes=(2,1))
print(np_dot.shape)
print(np_dot)

(3, 2, 3)
[[[2.3 2.3 2.3]
  [3.  3.  3. ]]

 [[4.6 4.6 4.6]
  [6.  6.  6. ]]

 [[6.9 6.9 6.9]
  [9.  9.  9. ]]]


In [66]:
np.einsum('nij->nj', B,L)

ValueError: fewer operands provided to einstein sum function than specified in the subscripts string

In [60]:
tx, ax = [np.pi/3]*2, [np.pi/5]*2
kwargs = {'cos_ax': np.cos(ax), 
 'sin_ax': np.sin(ax), 
 'cos_tx': np.cos(tx), 
 'sin_tx': np.sin(tx)}
A = representation.data_to_image_matrix(**kwargs)
print("A\n",A)
print(A.shape)
B = representation.image_to_data_matrix(**kwargs)
print("inverse?\n",B) #only if xx+yy=aa+bb=1

A
 [[[ 0.70062927  0.70062927]
  [ 0.5         0.5       ]
  [ 0.          0.        ]]

 [[-0.4045085  -0.4045085 ]
  [ 0.8660254   0.8660254 ]
  [ 0.          0.        ]]

 [[ 0.58778525  0.58778525]
  [ 0.          0.        ]
  [ 1.          1.        ]]]
(3, 3, 2)
inverse?
 [[[ 1.07046627  1.07046627]
  [-0.61803399 -0.61803399]
  [ 0.          0.        ]]

 [[ 0.5         0.5       ]
  [ 0.8660254   0.8660254 ]
  [ 0.          0.        ]]

 [[-0.62920429 -0.62920429]
  [ 0.36327126  0.36327126]
  [ 1.          1.        ]]]
